import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen flex flex-col bg-white text-black`}
			>
				<div className="w-full flex justify-center">
					<h1 className="font-semibold text-center text-5xl my-6 bg-slate-300 w-fit px-4 py-2 rounded-2xl text-black">
						Language Learning App
					</h1>
				</div>
				<div className="flex flex-row w-full h-full mb-5">
					<div className="flex flex-col justify-center ml-2 mr-4 space-y-10 text-left">
						<Link
							className="border-2 border-purple-500 rounded px-2 hover:bg-purple-500 hover:text-white"
							href={"/"}
						>
							Home
						</Link>
						<Link
							className="border-2 border-pink-500 rounded px-2 hover:bg-pink-500 hover:text-white"
							href={"/stories"}
						>
							Stories
						</Link>
						<Link
							className="border-2 border-green-500 rounded px-2 hover:bg-green-500 hover:text-white"
							href={"/numbers"}
						>
							Numbers
						</Link>
						<Link
							className="border-2 border-blue-500 rounded px-2 hover:bg-blue-500 hover:text-white"
							href={"/assessments"}
						>
							Assessments
						</Link>
						<Link
							className="border-2 border-red-500 rounded px-2 hover:bg-red-500 hover:text-white"
							href={"/resources"}
						>
							Resources
						</Link>
						<Link
							className="border-2 border-orange-500 rounded px-2 hover:bg-orange-500 hover:text-white"
							href={"/time"}
						>
							Time
						</Link>
					</div>
					<div className="w-full mr-5">{children}</div>
				</div>
			</body>
		</html>
	);
}
